# Site settings
title: Carnal Panic
email: pete@gamache.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://petegamache.com" # the base hostname & protocol for your site
twitter_username: gamache
github_username:  gamache

# Build settings
markdown: kramdown
